name: tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x, 22.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: ./node_modules/.bin/ng test ng-rest-client --watch=false --browsers=ChromeHeadless --code-coverage
      - run: cd libs/ng-rest-client && npm run build:schematics && npx jasmine ../../dist/ng-rest-client/schematics/**/*.spec.js

